### ISSUE TITLE
很不错的插件哇，但要用的话把ImgCutter.vue复制到项目库就好了，不用npm i

### ISSUE THREAD

**Issue by newVincentFong** [acccccccb/vue-img-cutter#11]
`关键源码` [ /src/components/ImgCutter.vue](https://github.com/acccccccb/vue-img-cutter/blob/master/src/components/ImgCutter.vue)

整个项目是插件 + 插件展示页面的代码

复制的时候，把里面的import盖掉就好

**Comment by acccccccb** [comment]
> `关键源码` [ /src/components/ImgCutter.vue](https://github.com/acccccccb/vue-img-cutter/blob/master/src/components/ImgCutter.vue)
> 
> 整个项目是插件 + 插件展示页面的代码
> 
> 复制的时候，把里面的import盖掉就好

使用npm i方便以后更新哦
