### ISSUE TITLE
配置rate截图无法达到预期宽高

### ISSUE THREAD

**Issue by wang1139** [acccccccb/vue-img-cutter#15]
**bug描述**
自定义rate比例为宽比高小时，例如3:4，截图不全，底部丢失
**版本号**
2.1.2版本
**浏览器版本**
Chrome

**Comment by acccccccb** [comment]
收到 正在处理

**Comment by acccccccb** [comment]
请跟新至2.1.3

**Comment by wang1139** [comment]
比例1:10和10:10没问题，2:10到9:10还是截取不全


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "acccccccb/vue-img-cutter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 上午10:43
收件人:&nbsp;"acccccccb/vue-img-cutter"<vue-img-cutter@noreply.github.com&gt;;
抄送:&nbsp;"恭喜你获得腾讯官方"<1534205807@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [acccccccb/vue-img-cutter] 配置rate截图无法达到预期宽高 (#15)





 
收到 正在处理
