### ISSUE TITLE
如果没有选取图片直接点击确定，也能触发裁剪函数

### ISSUE THREAD

**Issue by curiousBeginner** [acccccccb/vue-img-cutter#16]
**bug描述**
完成截图：cutDown 回调，能够加入是否上传并且裁剪判断，我测试发现一个问题就是我没有上传图片直接可以点击确定按钮，并且在回调函数能取到值，只是没有fileName参数，我没有上传就不应该触发裁剪功能。这里我通过判断fileName能够阻止他的上传。但是有种情况就是我上传图片但是取消本次裁剪，因为浏览器的机制原因，input的files队列没有被清空，我再次打开裁剪，并且不上传图片，我点击裁剪的确定按钮过后获取的对象就会有fileName，这里我就没办反判断是否上传本次结果了，因为我没有办法监听input的change事件，所以我的图片裁剪我是没办法是否判断是否是有效裁剪。如果出现我上述问题就会出现一张空白图片.
**版本号**
最新版
**浏览器版本**
IE/Edge/Firefox/Chrome

**Comment by acccccccb** [comment]
收到 正在处理

**Comment by acccccccb** [comment]
请跟新至2.1.3
