### ISSUE TITLE
能否增加类似微信的文字插入和剪头功能？

### ISSUE THREAD

**Issue by huangssssx** [acccccccb/vue-img-cutter#23]
**bug描述**
详细描述bug是在什么操作下出现的，最好带上截图，如果可以线上预览，请附上链接
**版本号**
此bug出现在哪个版本
**浏览器版本**
IE/Edge/Firefox/Chrome

**Comment by acccccccb** [comment]
@huangssssx 现在已可以在指定位置添加自定义样式的水印文字，后续会考虑加入你建议的功能
