### ISSUE TITLE
裁剪选择框位置

### ISSUE THREAD

**Issue by longliangjun** [acccccccb/vue-img-cutter#25]
**bug描述**
不是bug，我想问下 我想记录用户最后拖动裁剪框的位置，下次裁剪会记录下来，但是我总找不到x 和 y的公用值，要么就是裁剪框位置变化了 但是截取的图像位置没有变化
**版本号**
此bug出现在哪个版本
最新版本

**Comment by acccccccb** [comment]
@longliangjun 更新至2.1.10并设置saveCutPosition=true
