### ISSUE TITLE
原图裁剪？

### ISSUE THREAD

**Issue by Littleor** [acccccccb/vue-img-cutter#29]
你好，我在代码中发现了这些内容：
组件有`originalGraph`和`cuttingOriginal`两个属性但是`cuttingOriginal`并没有被使用，请问是冗余字段还是我个人理解偏差？
然后想了解下`originalGraph`的具体内涵是什么？为什么会有裁剪原图的选项？

**Comment by acccccccb** [comment]
**应用在第1075行，当这个字段为false时，截图的图像大小等于裁剪框的大小，为true时，截取的图像等于裁剪框尺寸/图片缩小倍数**
// 原图裁剪 originalGraph
if(_this.originalGraph==true) {
    let scale = _this.drawImg.width / _this.drawImg.swidth;
    // 计算实际图像大小
    let transWidth = _this.toolBox.width/scale;
    let transHeight = _this.toolBox.height/scale;
    newCanv.width = transWidth;
    newCanv.height = transHeight;
    // 重新计算裁剪坐标
    let sx = (_this.toolBox.x-_this.drawImg.x)/scale;
    let sy = (_this.toolBox.y-_this.drawImg.y)/scale;
    let swidth = _this.drawImg.swidth;
    let sheight = _this.drawImg.sheight;
    // TODO 使原图裁剪支持旋转后的图像
    // ctx.translate(sx + transWidth/2, sy + transHeight/2);
    // ctx.rotate((_this.rotateImg.angle) * Math.PI / 180);
    // ctx.translate(-(sx + transWidth/2), -(sy + transHeight/2));
    ctx.translate(-sx, -sy);
    ctx.drawImage(_this.drawImg.img, 0, 0, swidth, sheight);
}

**Comment by Littleor** [comment]
> **应用在第1075行，当这个字段为false时，截图的图像大小等于裁剪框的大小，为true时，截取的图像等于裁剪框尺寸/图片缩小倍数**
> 
> ```js
>                                         // 原图裁剪 originalGraph
>                                         if(_this.originalGraph==true) {
>                                             let scale = _this.drawImg.width / _this.drawImg.swidth;
> 
>                                             // 计算实际图像大小
>                                             let transWidth = _this.toolBox.width/scale;
>                                             let transHeight = _this.toolBox.height/scale;
>                                             newCanv.width = transWidth;
>                                             newCanv.height = transHeight;
>                                             // 重新计算裁剪坐标
>                                             let sx = (_this.toolBox.x-_this.drawImg.x)/scale;
>                                             let sy = (_this.toolBox.y-_this.drawImg.y)/scale;
> 
>                                             let swidth = _this.drawImg.swidth;
>                                             let sheight = _this.drawImg.sheight;
>                                             // TODO 使原图裁剪支持旋转后的图像
>                                             // ctx.translate(sx + transWidth/2, sy + transHeight/2);
>                                             // ctx.rotate((_this.rotateImg.angle) * Math.PI / 180);
>                                             // ctx.translate(-(sx + transWidth/2), -(sy + transHeight/2));
>                                             ctx.translate(-sx, -sy);
>                                             ctx.drawImage(_this.drawImg.img, 0, 0, swidth, sheight);
>                                         } else {
> ```



> **应用在第1075行，当这个字段为false时，截图的图像大小等于裁剪框的大小，为true时，截取的图像等于裁剪框尺寸/图片缩小倍数**
> 
> ```js
>                                         // 原图裁剪 originalGraph
>                                         if(_this.originalGraph==true) {
>                                             let scale = _this.drawImg.width / _this.drawImg.swidth;
> 
>                                             // 计算实际图像大小
>                                             let transWidth = _this.toolBox.width/scale;
>                                             let transHeight = _this.toolBox.height/scale;
>                                             newCanv.width = transWidth;
>                                             newCanv.height = transHeight;
>                                             // 重新计算裁剪坐标
>                                             let sx = (_this.toolBox.x-_this.drawImg.x)/scale;
>                                             let sy = (_this.toolBox.y-_this.drawImg.y)/scale;
> 
>                                             let swidth = _this.drawImg.swidth;
>                                             let sheight = _this.drawImg.sheight;
>                                             // TODO 使原图裁剪支持旋转后的图像
>                                             // ctx.translate(sx + transWidth/2, sy + transHeight/2);
>                                             // ctx.rotate((_this.rotateImg.angle) * Math.PI / 180);
>                                             // ctx.translate(-(sx + transWidth/2), -(sy + transHeight/2));
>                                             ctx.translate(-sx, -sy);
>                                             ctx.drawImage(_this.drawImg.img, 0, 0, swidth, sheight);
>                                         } else {
> ```

明白了～
感谢🙏
