### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.     at VueComponent.cropPicture 

### ISSUE THREAD

**Issue by xqmm** [acccccccb/vue-img-cutter#42]
**bug描述**
 弹出裁剪框后浏览器报：Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at VueComponent.cropPicture 
**版本号**
 2.2.3版本
**浏览器版本**
 Chrome

**Comment by acccccccb** [comment]
@xqmm 是vue3吗

**Comment by keke195** [comment]
我也是这错，我没有使用远程图片裁剪，怎么解决啊
