### ISSUE TITLE
关于<template>中this的问题

### ISSUE THREAD

**Issue by littleH0** [acccccccb/vue-img-cutter#45]
![image](https://user-images.githubusercontent.com/67537146/130016711-98ee36ee-a6fa-4b35-9eba-73cdfcf53525.png)
![image](https://user-images.githubusercontent.com/67537146/130017054-154d4395-27be-4424-b0b9-4c73a3b0ce3c.png)
你好，源码在template中使用props中的值时某些前面加了this(截图只是一个变量，还有其它的一些)，使用时运行不了，去掉就可以运行，麻烦看一下可以吗？谢谢

**Comment by acccccccb** [comment]
感谢反馈，我大意了，不知什么时候写的
