### ISSUE TITLE
裁剪远程地址图片会报错

### ISSUE THREAD

**Issue by halfsouli** [acccccccb/vue-img-cutter#46]
![image](https://user-images.githubusercontent.com/59306814/130061824-b0713e83-2ffc-472e-a87f-c2668361f68a.png)
Error in v-on handler: "SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."

found in

---> <ImgCutter> at node_modules/_vue-img-cutter@2.2.4@vue-img-cutter/src/components/ImgCutter.vue

**Comment by acccccccb** [comment]
crossOrigin 设置为 true，  crossOriginHeader 设置为 * ，同时图片服务器需要将 Access-Control-Allow-Origin 设置为 *
