### ISSUE TITLE
图片过大情况下，点击scale，只能通过鼠标滚动回到载入时的大小

### ISSUE THREAD

**Issue by Roqii** [acccccccb/vue-img-cutter#48]
**bug描述**
上传4K图片进行剪裁，点击scale后，无法快速缩小图片。
![image](https://user-images.githubusercontent.com/5799590/133716753-a6eee45b-1efa-40f3-a628-af2ecd4e4d72.png)

``
**版本号**
2.2.5
**浏览器版本**
Chrome

**Comment by acccccccb** [comment]
我放假了看看
