### ISSUE TITLE
初始化项目报loaders错误

### ISSUE THREAD

**Issue by yuArimer** [acccccccb/vue-img-cutter#51]
**bug描述**
项目初始化的时候，运行起来报调用组件的loader问题

ERROR in ./node_modules/vue-img-cutter/src/components/ImgCutter.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|     <div>
|         <div @click="handleOpen" v-if="showChooseBtn === true && isModal === true">

**版本号**
3.0.0
**浏览器版本**
Chrome

**Comment by acccccccb** [comment]
你有安装vue-loader和vue-template-compiler吗，提供一个demo给我看看

**Comment by acccccccb** [comment]
你的vue版本是多少 需要 vue@3.2.x
