### ISSUE TITLE
弹窗模式下选择图片按钮隐藏不了

### ISSUE THREAD

**Issue by vivoX9** [acccccccb/vue-img-cutter#53]
**bug描述**
详细描述bug是在什么操作下出现的，最好带上截图，如果可以线上预览，请附上链接
**版本号**
此bug出现弹窗模式下选择图片按钮隐藏不了在哪个版本
**浏览器版本**
IE/Edge/Firefox/Chrome

**Comment by acccccccb** [comment]
> **bug描述** 详细描述bug是在什么操作下出现的，最好带上截图，如果可以线上预览，请附上链接 **版本号** 此bug出现�弹窗模式下选择图片按钮隐藏不了在哪个版本 **浏览器版本** IE/Edge/Firefox/Chrome

没有重现，你可以使用 深度选择器隐藏按钮

/deep/ .vue-img-cutter .btn { display:none; }
