### ISSUE TITLE
vue3使用该组件初始化显示图片，使用handleOpen报错

### ISSUE THREAD

**Issue by zhengwenlin** [acccccccb/vue-img-cutter#58]
![image](https://user-images.githubusercontent.com/37999111/159864963-ffc26b2e-b862-40e5-8f49-da020f2dd9be.png)
runtime-core.esm-bundler.js?5c40:218 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported

**Comment by acccccccb** [comment]
> ![image](https://user-images.githubusercontent.com/37999111/159864963-ffc26b2e-b862-40e5-8f49-da020f2dd9be.png) runtime-core.esm-bundler.js?5c40:218 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported

所使用的图片是否是图片链接而非本地选取，如果是，则需要设置以下参数：crossOrigin="true" rossOriginHeader="*"
参考：https://github.com/acccccccb/vue-img-cutter/blob/master/README-zh-CN.md
