### ISSUE TITLE
原图裁剪,怎样才能支持旋转功能？

### ISSUE THREAD

**Issue by abcabcabc111122222** [acccccccb/vue-img-cutter#59]
需要原图裁剪，并且还要旋转功能，要怎么实现？救救这可怜的前端......

**Comment by abcabcabc111122222** [comment]
需要原图裁剪，并且还要旋转功能，要怎么实现？救救这可怜的前端......

**Comment by acccccccb** [comment]
> 需要原图裁剪，并且还要旋转功能，要怎么实现？救救这可怜的前端......

原图裁剪旋转坐标计算太复杂了我也没写出来...

**Comment by zxlovezly** [comment]
我也需要原图裁切后支持旋转，用户在催，然而我加了原图质量输出后，旋转就没了。救救可怜的前端......

**Comment by acccccccb** [comment]
> 我也需要原图裁切后支持旋转，用户在催，然而我加了原图质量输出后，旋转就没了。救救可怜的前端......

图片大小是否超出屏幕？如果没有超出，把裁剪画布设置为屏幕宽高怎么样
