### ISSUE TITLE
工具栏度数宽度不够

### ISSUE THREAD

**Issue by GreenSkinGhost** [acccccccb/vue-img-cutter#64]
**bug描述**
详细描述bug是在什么操作下出现的，最好带上截图，如果可以线上预览，请附上链接
**版本号**
此bug出现在哪个版本
**浏览器版本**
IE/Edge/Firefox/Chrome
![image](https://user-images.githubusercontent.com/79361776/172811355-a6bdd448-dd0a-4c73-94e9-7d025b97fbe3.png)

**Comment by GreenSkinGhost** [comment]
会造成点击不到按钮而滚动不了

**Comment by acccccccb** [comment]
下个版本修复
