### ISSUE TITLE
报错:Uncaught TypeError: Cannot set property name of #<File> which has only a getter

### ISSUE THREAD

**Issue by idlesysman** [acccccccb/vue-img-cutter#75]
**bug描述**
如果上传图片的width和height小于等于组件设置的 宽度和高度就会报错：

> Uncaught TypeError: Cannot set property name of #<File> which has only a getter

**版本号**
2.2.5
**浏览器版本**
Chrome

**Comment by idlesysman** [comment]
我这报错时设置的宽度和宽度是150X150

**Comment by acccccccb** [comment]
@idlesysman 没有重现 把代码贴出来看看

**Comment by idlesysman** [comment]
`
 <ImgCutter
          :cut-width="135"
          :cut-height="135"
          :is-modal="true"
          :size-change="false"
          :small-to-upload="true"
          @cutDown="cutDown"
        >
          <button slot="open">设置照片</button>
        </ImgCutter>

    cutDown(imageCute) {
      const arr = imageCute.dataURL.split(';')
      this.one.photoType = arr[0].split(':')[1]
      this.one.photoBase64 = arr[1].split(',')[1]
      this.one.profilePhoto = imageCute.dataURL
    },

`
