### ISSUE TITLE
可不可以在文件上传的accept 中加上webp

### ISSUE THREAD

**Issue by Hocheese** [acccccccb/vue-img-cutter#80]
现在要打开webp格式的文件，要手动选择“所有文件”，对用户来说非常麻烦

**Comment by acccccccb** [comment]
你可以将/src/components/ImgCutter.vue文件复制到你的项目中，并修改第215行
`accept="image/gif, image/jpeg ,image/png"` 
修改为
`accept="accept="image/gif, image/jpeg, image/png, image/webp""` 

下个版本我会把这个配置加上
